import Sidebar from "../../components/sidebar/Sidebar";
import { ClerkProvider } from "@clerk/nextjs";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Sidebar />
          <div className="App">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
